name: CI/CD
run-name: ${{ github.sha }} of branch ${{ github.ref }} by @${{ github.actor }}

on:
 push:
  branches:
   - pom-update

permissions:
 contents: write

jobs:
 clean-compile:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4
     
   - name: Setup JDK 21
     uses: actions/setup-java@v4
     with:
      java-version: '21'
      distribution: adopt

   - name: Clean n'' Compile project
     id: clean-compile-citizen
     run: mvn clean compile

 clean-install-no-tests:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup JDK 21
     uses: actions/setup-java@v2
     with:
      java-version: '21'
      distribution: adopt

   - name: Clean n'' Install project
     id: clean-compile-citizen
     run: mvn clean install -DskipTests
 
